### ISSUE TITLE
Deo machina does nothing

### ISSUE THREAD

**Issue by Muncher2112** [Muncher2112/Interbay#10]
#### Description of issue

Deo machina is the supposed "religion of the land" with arbiters to enforce it's will, but it doesn't have any will to enforce.  We will assume deo machina is some long surviving AI who has taken care of the station, and become it's god.

#### Difference between expected and actual behavior

Deo Machina should have some impact on the round.  It will request things, forbid things, reward the crew for doing things like branding heretics, or fulfilling requests, etc.  This + old god changes will give arbiters something to do beyond ask people if they know the prayer over and over.

#### TODO:
Way to interface with Deo Machina
Way to receive demands or possible actions
Way to deliver rewards or punishments

**Comment by Dekkar1218** [comment]
Could make it act similiar to the "throne room" in lifeweb, where the Deo Machina entitiy could be the "AI CORE" and the Magistrate and Overseer or anything with top dog clearance can interface with it using their ID. After interfacing with it, can change noble directives, deny or allow power to certain areas, make 'worship' announcement to praise the AI that saved humanity from itself. 

The Deo Machina can deliver demands like using cargo to send power cells, or power related items to the great machine city, where the AI overlord would reward the station with money, free power, food or weapons. 

Failure could mean the Machine City sending a deathsquad(either brainwashed humans, or robot constructs) , or inspector of some sort to check on the Magistrates progress.

This kinda fits in the setting I had for post apocalyptic where Deo Machina though a great AI overlord of the remants of humanity is still soley reliant on humanity to function through manual labor and power contributions. Thus the religious entity Deo machina was created in essence of the "Old Gods" like the holy bible, to brainwash and create utter servants of loyal humans. So in essence, the people that worship "Deo Machina" are brainwashed puppets for a machine, where people who worship old gods are more free minded - albeit violent given some of their religious practices.

So it's like Terminator, except instead of robots annihalting humanity, it uses them as pawns and sources of energy kinda like the AI in The Matrix .
